#!/usr/bin/env python3
"""Atlas — Python installer (cross-platform).

A single installer that detects the host OS and runs the *same* install flow
with OS-correct mechanisms:

    configure .env → collect NVIDIA keys (interactive, min 6)
    → install + start the service   (systemd on Linux, launchd on macOS,
                                     Windows Service on Windows)
    → install the atlas CLI         (symlink on Unix, atlas.cmd on Windows)
    → wire ANTHROPIC_*              (shell rc on Unix, setx on Windows)
    → ensure Claude Code            (curl|bash on Unix, irm|iex on Windows)
    → health-check the running proxy → launch claude.

The proxy itself (proxy/*.py) is untouched by this layer — it boots with one
portable command, `<venv-python> -m proxy.atlas_proxy`, which every service
backend wraps. Atlas is the NVIDIA-only proxy on port 8788.
"""
import os
import sys
import json
import shutil
import time
import platform
import subprocess
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

console = Console()

# ── Platform detection ────────────────────────────────────────────────────
# One source of truth for every OS branch in this file. platform.system()
# returns "Linux" / "Darwin" (macOS) / "Windows".
IS_LINUX = platform.system() == "Linux"
IS_MACOS = platform.system() == "Darwin"
IS_WINDOWS = platform.system() == "Windows"
IS_UNIX = IS_LINUX or IS_MACOS  # POSIX-ish: bash, symlinks, rc files, execvp

# Resolve PROJECT_DIR as the parent of this file's directory.
PROJECT_DIR = Path(__file__).resolve().parent.parent
VENV_DIR = PROJECT_DIR / ".venv"


def _venv_bin() -> Path:
    """The venv's executables directory: `bin` on Unix, `Scripts` on Windows."""
    return VENV_DIR / ("Scripts" if IS_WINDOWS else "bin")


def _venv_python() -> Path:
    """The venv's python interpreter: `bin/python` on Unix, `Scripts/python.exe`
    on Windows. All downstream code (service units, CLI invocation, token
    tracker) routes through this so venv paths are correct on every OS."""
    return _venv_bin() / ("python.exe" if IS_WINDOWS else "python")


PYTHON_BIN = _venv_python()

# Linux systemd unit (template). Only ever installed on Linux.
UNIT_SRC = PROJECT_DIR / "systemd" / "atlas-proxy.service"
UNIT_DST = Path("/etc/systemd/system/atlas-proxy.service")
SERVICE_NAME = "atlas-proxy.service"

# macOS LaunchAgent (template). Only ever installed on macOS.
PLIST_SRC = PROJECT_DIR / "setup" / "com.atlas.proxy.plist"
PLIST_LABEL = "com.atlas.proxy"

# Windows Service. Only ever installed on Windows.
WIN_SERVICE_MODULE = PROJECT_DIR / "setup" / "atlas_windows_service.py"
WIN_SERVICE_NAME = "AtlasProxy"
WIN_SERVICE_DISPLAY = "Atlas NVIDIA Proxy"

# CLI source (bash) — stays the Linux/macOS command. Untouched by this layer.
CLI_SRC = PROJECT_DIR / "bin" / "atlas"
CLI_DST = Path("/usr/local/bin/atlas")  # Unix symlink target
# Windows CLI shim — independent of the bash bin/atlas.
WIN_CLI_SRC = PROJECT_DIR / "bin" / "atlas.cmd"

ENV_FILE = PROJECT_DIR / ".env"
DEFAULT_KEYS_FILE = PROJECT_DIR / "data" / "keys.txt"

PROXY_URL = "http://127.0.0.1:8788"
MIN_KEYS = 6
CLAUDE_INSTALL_URL = "https://claude.ai/install.sh"
CLAUDE_INSTALL_PS_URL = "https://claude.ai/install.ps1"

DEFAULT_ENV = f"""\
# Atlas — NVIDIA-only proxy environment defaults
# Generated by setup/installer.py — paths resolve from this repo location,
# so this file is portable. Edit freely; installer won't overwrite an existing .env.
ATLAS_PROXY_HOST=127.0.0.1
ATLAS_PROXY_PORT=8788
# ATLAS_KEYS_FILE intentionally omitted — proxy defaults to
# {DEFAULT_KEYS_FILE} (resolved from its own __file__), correct on any
# machine. Uncomment + set only to relocate the keys file off the default path.
# ATLAS_KEYS_FILE={DEFAULT_KEYS_FILE}
ATLAS_NVIDIA_BASE_URL=https://integrate.api.nvidia.com/v1/chat/completions
ATLAS_NVIDIA_MODEL=z-ai/glm-5.2
ATLAS_PROXY_RELOAD_SECONDS=5
ATLAS_PROXY_MAX_KEY_FAILOVERS=3
ATLAS_PROXY_COOLDOWN_SECONDS=60
ATLAS_PROXY_REQUEST_TIMEOUT=300
ATLAS_PROXY_MAX_RETRIES=2
ATLAS_PROXY_DEBUG=0
"""


def _run(cmd, **kwargs):
    """Run a command, streaming output to the console."""
    return subprocess.run(cmd, check=True, **kwargs)


def _sudo_run(cmd, **kwargs):
    """Run a command via sudo if we're not root, else directly. Linux only —
    on macOS /usr/local/bin is user-writable and there's no need for sudo in
    the installer's paths; on Windows sudo doesn't exist. Guarded so this is
    a safe no-op-prefixed call site on non-root Linux only."""
    if IS_LINUX and os.geteuid() != 0:
        cmd = ["sudo", *cmd]
    return _run(cmd, **kwargs)


def _detect_user() -> tuple[str, str]:
    """Detect (username, home_dir) for the systemd unit's User= and HOME=.

    Linux only. The service should run as the invoking user, not blindly as
    root. When the installer is run under sudo, the real user is in SUDO_USER;
    otherwise it's the current euid's name. Home is that user's passwd entry,
    not $HOME (which under sudo points at /root). Falls back to root if
    detection fails so the unit still installs rather than crashing — but the
    common case (a human running `sudo bash install.sh`) resolves to that
    human's account.
    """
    import getpass
    import pwd

    username = os.environ.get("SUDO_USER") or getpass.getuser()
    try:
        pw = pwd.getpwnam(username)
        return username, pw.pw_dir
    except KeyError:
        # Couldn't resolve — fall back to root so the unit still writes.
        return "root", "/root"


def _render_unit(unit_text: str) -> str:
    """Substitute __VAR__ placeholders in the systemd unit template.

    All path-dependent fields resolve from PROJECT_DIR + the detected user, so
    the generated unit has zero hardcoded /root or /home literals and works no
    matter where the repo is checked out or who installed it.
    """
    user, home = _detect_user()
    venv_bin = str(_venv_bin())
    venv_python = str(PYTHON_BIN)
    return (
        unit_text
        .replace("__ATLAS_USER__", user)
        .replace("__ATLAS_HOME__", home)
        .replace("__PROJECT_DIR__", str(PROJECT_DIR))
        .replace("__VENV_BIN__", venv_bin)
        .replace("__VENV_PYTHON__", venv_python)
    )


def _render_plist(plist_text: str) -> str:
    """Substitute __VAR__ placeholders in the macOS LaunchAgent plist template.
    Same substitution scheme as the systemd unit, minus the User= field (user
    agents run as the invoking user automatically)."""
    home = str(Path.home())
    return (
        plist_text
        .replace("__ATLAS_HOME__", home)
        .replace("__PROJECT_DIR__", str(PROJECT_DIR))
        .replace("__VENV_PYTHON__", str(PYTHON_BIN))
    )


def _is_valid_key(token: str) -> bool:
    """Match the sole validation gate in proxy/nvidia_client.py: a non-empty
    token starting with 'nvapi-'. No length or charset requirement."""
    return bool(token and token.startswith("nvapi-"))


def _resolve_keys_file() -> Path:
    """Resolve the keys file path from .env if present, else the default."""
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line.startswith("ATLAS_KEYS_FILE=") and not line.startswith("#"):
                val = line.split("=", 1)[1].strip()
                if val:
                    return Path(val)
    return DEFAULT_KEYS_FILE


def _read_existing_keys(keys_file: Path) -> list[str]:
    """Read keys_file, returning only valid nvapi- tokens, deduped, order preserved."""
    if not keys_file.exists():
        return []
    seen: set[str] = set()
    out: list[str] = []
    for raw in keys_file.read_text().splitlines():
        tok = raw.strip()
        if _is_valid_key(tok) and tok not in seen:
            seen.add(tok)
            out.append(tok)
    return out


def _write_keys(keys_file: Path, keys: list[str]) -> None:
    """Write keys one-per-line, 0600, parent dir created if missing."""
    keys_file.parent.mkdir(parents=True, exist_ok=True)
    keys_file.write_text("\n".join(keys) + ("\n" if keys else ""))
    keys_file.chmod(0o600)


def configure_env_defaults() -> None:
    """Create .env with ATLAS_* defaults if it does not already exist."""
    console.print(Panel.fit("[bold cyan]Configuring .env defaults[/]", border_style="cyan"))

    if ENV_FILE.exists():
        console.print(f"[yellow].env already exists — not overwriting:[/yellow] {ENV_FILE}")
        return

    ENV_FILE.write_text(DEFAULT_ENV)
    console.print(f"[green]Wrote default .env:[/green] {ENV_FILE}")


def collect_keys() -> None:
    """Interactively collect NVIDIA API keys. Requires at least MIN_KEYS valid
    nvapi- tokens. If keys.txt already has >= MIN_KEYS valid keys, skip entry
    (non-destructive). If stdin is not a TTY and keys are short, warn and skip
    rather than hang — the proxy tolerates an empty keys file and hot-reloads."""
    console.print(Panel.fit(
        f"[bold cyan]NVIDIA API keys (min {MIN_KEYS})[/]", border_style="cyan"))

    keys_file = _resolve_keys_file()
    existing = _read_existing_keys(keys_file)
    console.print(f"Keys file: [cyan]{keys_file}[/]")
    console.print(f"Existing valid keys: [green]{len(existing)}[/]")

    if len(existing) >= MIN_KEYS:
        console.print(
            f"[green]Found {len(existing)} keys (>= {MIN_KEYS}) — skipping entry.[/green]")
        # Rewrite deduped/cleaned set back only if it differs from disk.
        on_disk = [ln.strip() for ln in keys_file.read_text().splitlines()] if keys_file.exists() else []
        if on_disk != existing:
            _write_keys(keys_file, existing)
            console.print("[dim]Rewrote keys file (removed blanks/dupes/invalid lines).[/dim]")
        return

    need = MIN_KEYS - len(existing)
    console.print(
        f"[yellow]Need {need} more key(s) to reach the minimum of {MIN_KEYS}.[/yellow]")
    console.print(
        f"Paste each key on its own line. Enter a blank line or 'done' to finish.")
    console.print(
        f"[bold cyan]Where to get NVIDIA API keys:[/bold cyan]\n"
        f"  Get NVIDIA API keys from [link=https://build.nvidia.com/explore/discover]https://build.nvidia.com/explore/discover[/link]\n"
        f"  You will need at least {MIN_KEYS} API keys (separate accounts).\n"
        f"  Use [link=https://www.agentmail.to]https://www.agentmail.to[/link] for throwaway emails.\n"
        f"  Each key starts with 'nvapi-'.")

    if not sys.stdin.isatty():
        console.print(
            "[red]stdin is not a TTY — cannot prompt for keys interactively.[/red]\n"
            f"[yellow]Proceeding with {len(existing)} key(s). The proxy will start "
            "and hot-reload keys once you add them to the file.[/yellow]")
        if existing:
            _write_keys(keys_file, existing)
        return

    collected: list[str] = []
    seen: set[str] = set(existing)
    while True:
        remaining = MIN_KEYS - (len(existing) + len(collected))
        prompt = f"  key {len(collected) + 1}"
        if remaining > 0:
            prompt += f" ({remaining} more needed)"
        prompt += " > "
        try:
            raw = input(prompt)
        except EOFError:
            raw = ""
        tok = raw.strip()
        if tok == "" or tok.lower() == "done":
            total = len(existing) + len(collected)
            if total < MIN_KEYS:
                console.print(
                    f"[red]Only {total} key(s), need {MIN_KEYS}. "
                    "Keep entering or the proxy will have no keys to serve.[/red]")
                if tok == "":
                    continue
            break
        if not _is_valid_key(tok):
            console.print(
                f"[red]Invalid — key must start with 'nvapi-'. Try again.[/red]")
            continue
        if tok in seen:
            console.print("[yellow]Duplicate — already have that key. Skipping.[/yellow]")
            continue
        seen.add(tok)
        collected.append(tok)
        console.print(f"[green]Accepted.[/green] ({len(existing) + len(collected)} total)")

    merged = existing + collected
    _write_keys(keys_file, merged)
    console.print(f"[green]Wrote {len(merged)} keys to:[/green] {keys_file}")


def install_and_start_service() -> None:
    """Install + start the proxy service using the host's native mechanism.

    Dispatcher: systemd on Linux, launchd on macOS, Windows Service on Windows.
    Each backend wraps the same portable proxy command —
    `<venv-python> -m proxy.atlas_proxy` — so the proxy layer is identical
    across OSes; only the supervisor differs. The service is live (and survives
    reboot) by the time this step finishes.
    """
    if IS_LINUX:
        _install_systemd_unit()
    elif IS_MACOS:
        _install_launchd_agent()
    elif IS_WINDOWS:
        _install_windows_service()
    else:
        console.print(
            f"[yellow]Unsupported OS: {platform.system()}.[/yellow]\n"
            "The proxy still runs via `python -m proxy.atlas_proxy`; install a "
            "service supervisor manually if you want reboot persistence.")


def _install_systemd_unit() -> None:
    """Linux: install atlas-proxy.service, daemon-reload, then enable + start it.

    Behavior preserved exactly from the pre-cross-platform installer — same
    template render, same /etc/systemd/system destination, same enable --now.
    """
    console.print(Panel.fit(
        "[bold cyan]Installing + starting systemd unit (Linux)[/]", border_style="cyan"))

    if not UNIT_SRC.exists():
        console.print(f"[red]Unit source not found:[/red] {UNIT_SRC}")
        return

    unit_text = _render_unit(UNIT_SRC.read_text())

    if shutil.which("systemctl") is None:
        console.print(
            "[yellow]systemctl not found on this system — skipping unit install.[/yellow]\n"
            "Install atlas-proxy.service into /etc/systemd/system manually if needed.")
        return

    # Write the unit file (via sudo tee if not root).
    if os.geteuid() == 0:
        UNIT_DST.write_text(unit_text)
    else:
        subprocess.run(
            ["sudo", "tee", str(UNIT_DST)],
            input=unit_text,
            text=True,
            stdout=subprocess.DEVNULL,
            check=True,
        )

    console.print(f"[green]Wrote unit:[/green] {UNIT_DST}")
    _sudo_run(["systemctl", "daemon-reload"])
    console.print("[green]systemctl daemon-reload complete[/green]")

    # Enable + start now. Non-fatal: warn on failure, keep going.
    try:
        _sudo_run(["systemctl", "enable", "--now", SERVICE_NAME])
        console.print(f"[green]Enabled + started:[/green] {SERVICE_NAME}")
    except subprocess.CalledProcessError:
        console.print(
            f"[red]Failed to enable/start {SERVICE_NAME}.[/red] "
            "Run `atlas start` manually once keys are present.")

    # Report resulting state.
    try:
        active = subprocess.run(
            ["systemctl", "is-active", SERVICE_NAME],
            capture_output=True, text=True,
        ).stdout.strip()
        console.print(f"[dim]Service state: {active}[/dim]")
    except subprocess.CalledProcessError:
        pass


def _install_launchd_agent() -> None:
    """macOS: render the LaunchAgent plist to ~/Library/LaunchAgents/, load it,
    and start the proxy. User agent — no sudo needed, survives reboot."""
    console.print(Panel.fit(
        "[bold cyan]Installing + starting launchd agent (macOS)[/]", border_style="cyan"))

    if not PLIST_SRC.exists():
        console.print(f"[red]plist template not found:[/red] {PLIST_SRC}")
        return

    plist_text = _render_plist(PLIST_SRC.read_text())
    launch_dir = Path.home() / "Library" / "LaunchAgents"
    launch_dir.mkdir(parents=True, exist_ok=True)
    plist_dst = launch_dir / f"{PLIST_LABEL}.plist"
    plist_dst.write_text(plist_text)
    console.print(f"[green]Wrote LaunchAgent:[/green] {plist_dst}")

    # Unload if already loaded so we re-bind cleanly to the new plist.
    subprocess.run(["launchctl", "unload", str(plist_dst)],
                   capture_output=True, text=True)

    try:
        _run(["launchctl", "load", "-w", str(plist_dst)])
        console.print(f"[green]Loaded LaunchAgent:[/green] {PLIST_LABEL}")
    except subprocess.CalledProcessError:
        console.print(
            f"[red]Failed to load LaunchAgent {PLIST_LABEL}.[/red] "
            "Run `atlas start` manually once keys are present.")
        return

    try:
        _run(["launchctl", "start", PLIST_LABEL])
        console.print(f"[green]Started:[/green] {PLIST_LABEL}")
    except subprocess.CalledProcessError:
        console.print(
            f"[red]Failed to start {PLIST_LABEL}.[/red] "
            "Run `launchctl start com.atlas.proxy` manually.")

    # Report resulting state.
    try:
        out = subprocess.run(
            ["launchctl", "list", PLIST_LABEL],
            capture_output=True, text=True, check=False,
        ).stdout.strip()
        if out:
            console.print(f"[dim]{out}[/dim]")
    except Exception:
        pass


def _install_windows_service() -> None:
    """Windows: pip-install pywin32 into the venv, then register + start the
    AtlasProxy Windows Service via the atlas_windows_service.py host module.
    The service host spawns `<venv-python> -m proxy.atlas_proxy` and manages
    its lifecycle — it never imports or modifies the proxy. Auto-start on boot
    is set by the service's own startup mode."""
    console.print(Panel.fit(
        "[bold cyan]Installing + starting Windows Service (Windows)[/]",
        border_style="cyan"))

    if not WIN_SERVICE_MODULE.exists():
        console.print(f"[red]Service host not found:[/red] {WIN_SERVICE_MODULE}")
        return

    # pywin32 is Windows-only; install it into the venv (not the shared pin
    # file, so Linux/macOS installs never pull it).
    console.print("[dim]Installing pywin32 into the venv...[/dim]")
    pip = _venv_bin() / ("pip.exe" if IS_WINDOWS else "pip")
    try:
        _run([str(pip), "install", "pywin32"])
        console.print("[green]pywin32 installed.[/green]")
    except subprocess.CalledProcessError:
        console.print(
            "[red]Failed to install pywin32 — cannot register the Windows Service.[/red]")
        return

    # Register the service (idempotent: the host module handles re-install).
    try:
        _run([str(PYTHON_BIN), str(WIN_SERVICE_MODULE), "--install"])
        console.print(f"[green]Registered service:[/green] {WIN_SERVICE_NAME}")
    except subprocess.CalledProcessError:
        console.print(
            f"[red]Failed to register {WIN_SERVICE_NAME}.[/red] "
            "Run as Administrator, then re-run.")
        return

    # Start it now. Non-fatal: warn on failure, keep going.
    try:
        _run([str(PYTHON_BIN), str(WIN_SERVICE_MODULE), "--start"])
        console.print(f"[green]Started:[/green] {WIN_SERVICE_NAME}")
    except subprocess.CalledProcessError:
        console.print(
            f"[red]Failed to start {WIN_SERVICE_NAME}.[/red] "
            "Run `sc start AtlasProxy` manually once keys are present.")

    # Report resulting state.
    try:
        state = subprocess.run(
            ["sc", "query", WIN_SERVICE_NAME],
            capture_output=True, text=True, check=False,
        ).stdout.strip()
        if state:
            console.print(f"[dim]{state}[/dim]")
    except Exception:
        pass


def install_cli() -> None:
    """Install the `atlas` operator command. Unix: symlink
    /usr/local/bin/atlas -> bin/atlas (the bash CLI, which stays untouched).
    Windows: add the venv Scripts dir + bin dir to the user PATH so the
    atlas.cmd shim resolves. The bash bin/atlas is never modified."""
    console.print(Panel.fit("[bold cyan]Installing atlas CLI[/]", border_style="cyan"))

    if IS_WINDOWS:
        _install_cli_windows()
        return

    # Linux/macOS: symlink the bash CLI.
    if not CLI_SRC.exists():
        console.print(f"[red]CLI source not found:[/red] {CLI_SRC}")
        return

    CLI_SRC.chmod(0o755)

    # Remove an existing symlink/path at the destination if present.
    if CLI_DST.is_symlink() or CLI_DST.exists():
        _sudo_run(["rm", "-f", str(CLI_DST)])

    # On Linux, /usr/local/bin may need sudo; on macOS it's user-writable on
    # modern installs, and _sudo_run is a no-op prefix off-Linux-root.
    if IS_LINUX and os.geteuid() != 0:
        _sudo_run(["ln", "-s", str(CLI_SRC), str(CLI_DST)])
    else:
        try:
            _run(["ln", "-s", str(CLI_SRC), str(CLI_DST)])
        except subprocess.CalledProcessError:
            # Fall back to sudo if the direct symlink hits permissions.
            _sudo_run(["ln", "-s", str(CLI_SRC), str(CLI_DST)])
    console.print(f"[green]Linked CLI:[/green] {CLI_DST} -> {CLI_SRC}")


def _install_cli_windows() -> None:
    """Windows: ensure the atlas.cmd shim exists and put the venv Scripts dir
    + the repo bin dir on the user PATH via setx so `atlas` resolves in new
    shells. The shim drives the Windows Service via sc.exe and runs the token
    tracker through the venv python — independent of the bash bin/atlas."""
    if not WIN_CLI_SRC.exists():
        console.print(f"[red]Windows CLI shim not found:[/red] {WIN_CLI_SRC}")
        return

    # Add venv\Scripts and the repo bin dir to the user PATH (idempotent-ish:
    # setx writes the whole value, so we read current user PATH first).
    import winreg  # type: ignore  # Windows-only; only imported here.
    paths_to_add = [str(_venv_bin()), str(PROJECT_DIR / "bin")]
    try:
        with winreg.OpenKey(
            winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_READ
        ) as key:
            current, _ = winreg.QueryValueEx(key, "PATH")
    except OSError:
        current = os.environ.get("PATH", "")

    parts = [p for p in current.split(os.pathsep) if p]
    changed = False
    for p in paths_to_add:
        if p not in parts:
            parts.append(p)
            changed = True
    if changed:
        new_path = os.pathsep.join(parts)
        # setx truncates at 1024 chars; warn if we'd overflow.
        if len(new_path) > 1024:
            console.print(
                "[yellow]User PATH is near the setx 1024-char limit — "
                "adding bin dirs anyway, but verify in a new shell.[/yellow]")
        subprocess.run(["setx", "PATH", new_path], check=False,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        console.print(f"[green]Added to user PATH:[/green] "
                      f"{', '.join(paths_to_add)}")
    else:
        console.print("[yellow]CLI dirs already on PATH.[/yellow]")

    # Also apply to this process so the immediately-launched claude sees them.
    for p in paths_to_add:
        if p not in os.environ.get("PATH", "").split(os.pathsep):
            os.environ["PATH"] = p + os.pathsep + os.environ.get("PATH", "")
    console.print(f"[green]Windows CLI shim available:[/green] {WIN_CLI_SRC.name}")


def wire_claude_env() -> None:
    """Mandatory: write ANTHROPIC_* into the environment so Claude Code talks
    to the proxy, strip any stale ANTHROPIC_AUTH_TOKEN, and apply the exports
    to THIS process so the immediately-launched claude inherits them — no
    manual source needed.

    Unix: write to ~/.bashrc and ~/.zshrc (whichever exist). If neither exists,
    create ~/.bashrc so the block always lands somewhere.
    Windows: persist via setx (the user environment), which new shells inherit.
    """
    console.print(Panel.fit("[bold cyan]Wiring env[/]", border_style="cyan"))

    base_url = "http://127.0.0.1:8788"
    api_key = "atlas"

    if IS_WINDOWS:
        _wire_env_windows(base_url, api_key)
    else:
        _wire_env_unix(base_url, api_key)

    # Apply to THIS process immediately so the claude we exec next inherits the
    # exports without the user needing to source their rc / open a new shell.
    os.environ["ANTHROPIC_BASE_URL"] = base_url
    os.environ["ANTHROPIC_API_KEY"] = api_key
    os.environ.pop("ANTHROPIC_AUTH_TOKEN", None)
    console.print("[green]Exports applied to this process.[/green]")
    console.print("[dim]Future shells pick them up automatically.[/dim]")


def _wire_env_unix(base_url: str, api_key: str) -> None:
    """Linux/macOS: append the Atlas block to ~/.bashrc and ~/.zshrc."""
    candidates = [Path.home() / ".bashrc", Path.home() / ".zshrc"]
    rc_files = [p for p in candidates if p.exists()]
    if not rc_files:
        # No rc file at all — create .bashrc so the exports have a home.
        bashrc = Path.home() / ".bashrc"
        bashrc.touch()
        rc_files = [bashrc]
        console.print(f"[yellow]No rc file found — created:[/yellow] {bashrc}")

    # The Atlas block we ensure is present in every rc file.
    marker = "ANTHROPIC_BASE_URL=http://127.0.0.1:8788"
    block = (
        "\n# --- Atlas NVIDIA proxy (port 8788) ---\n"
        f"export ANTHROPIC_BASE_URL={base_url}\n"
        f"export ANTHROPIC_API_KEY={api_key}\n"
        "unset ANTHROPIC_AUTH_TOKEN\n"
        "# --- end Atlas ---\n"
    )

    for rc in rc_files:
        content = rc.read_text()

        # Strip any stale ANTHROPIC_AUTH_TOKEN line(s) so only base_url + api_key
        # remain authoritative. Claude Code honors ANTHROPIC_AUTH_TOKEN if set,
        # which would bypass the proxy — so we drop it.
        new_lines = []
        changed = False
        for line in content.splitlines():
            if line.strip().startswith("export ANTHROPIC_AUTH_TOKEN="):
                changed = True
                continue  # drop it
            new_lines.append(line)
        stripped = "\n".join(new_lines)
        if changed:
            console.print(f"[yellow]Removed stale ANTHROPIC_AUTH_TOKEN from:[/yellow] {rc}")

        # Append the Atlas block if not already wired.
        if marker not in stripped:
            if stripped and not stripped.endswith("\n"):
                stripped += "\n"
            stripped += block
            console.print(f"[green]Appended Atlas env exports to:[/green] {rc}")
        else:
            console.print(f"[yellow]Already wired in:[/yellow] {rc}")
        rc.write_text(stripped)


def _wire_env_windows(base_url: str, api_key: str) -> None:
    """Windows: persist ANTHROPIC_* into the user environment via setx and
    clear any stale ANTHROPIC_AUTH_TOKEN. setx is the Windows equivalent of
    appending to .bashrc — new shells inherit it."""
    for name, value in (("ANTHROPIC_BASE_URL", base_url),
                        ("ANTHROPIC_API_KEY", api_key)):
        subprocess.run(["setx", name, value], check=False,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        console.print(f"[green]setx {name}[/green] (persists for new shells)")
    # Clear a stale AUTH_TOKEN if present.
    subprocess.run(["reg", "delete", "HKCU\\Environment", "/v",
                    "ANTHROPIC_AUTH_TOKEN", "/f"], check=False,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    console.print("[green]Windows user env wired.[/green]")


def ensure_claude() -> str | None:
    """Ensure `claude` is on PATH. If missing, install via Anthropic's native
    installer — curl|bash on Unix, irm|iex via PowerShell on Windows. Returns
    the resolved claude path or None."""
    console.print(Panel.fit("[bold cyan]Ensuring Claude Code is installed[/]", border_style="cyan"))

    claude_path = shutil.which("claude")
    if claude_path:
        try:
            ver = subprocess.run(
                ["claude", "--version"], capture_output=True, text=True, check=False,
            ).stdout.strip()
            console.print(f"[green]claude found:[/green] {claude_path}" +
                          (f" ({ver})" if ver else ""))
        except Exception:
            console.print(f"[green]claude found:[/green] {claude_path}")
        return claude_path

    console.print("[yellow]claude not on PATH — installing via Anthropic native installer...[/yellow]")

    if IS_WINDOWS:
        return _ensure_claude_windows()

    # Unix: curl | bash.
    if shutil.which("curl") is None:
        console.print("[red]curl not found — cannot install claude automatically.[/red]")
        return None

    # Native installer writes ~/.local/bin/claude. Ensure it's on PATH for this process.
    local_bin = Path.home() / ".local" / "bin"
    if str(local_bin) not in os.environ.get("PATH", "").split(":"):
        os.environ["PATH"] = f"{local_bin}:{os.environ.get('PATH', '')}"

    try:
        _run(f"curl -fsSL {CLAUDE_INSTALL_URL} | bash", shell=True)
        console.print("[green]Claude Code install script finished.[/green]")
    except subprocess.CalledProcessError:
        console.print(
            "[red]Native installer failed.[/red] Install claude manually, then re-run.")
        return None

    claude_path = shutil.which("claude")
    if claude_path:
        console.print(f"[green]claude now available:[/green] {claude_path}")
        return claude_path

    console.print(
        f"[yellow]claude still not on PATH after install.[/yellow] "
        f"Check {local_bin} and ensure it's on your PATH.")
    return None


def _ensure_claude_windows() -> str | None:
    """Windows: install claude via `irm https://claude.ai/install.ps1 | iex`
    through PowerShell. The native installer drops claude into a per-user
    location; ensure that's on PATH for this process."""
    ps = shutil.which("pwsh") or shutil.which("powershell")
    if ps is None:
        console.print(
            "[red]No PowerShell found — cannot install claude automatically.[/red]\n"
            "Install Claude Code manually, then re-run.")
        return None

    try:
        _run([ps, "-NoProfile", "-Command",
              f"irm {CLAUDE_INSTALL_PS_URL} | iex"])
        console.print("[green]Claude Code install script finished.[/green]")
    except subprocess.CalledProcessError:
        console.print(
            "[red]Native installer failed.[/red] Install claude manually, then re-run.")
        return None

    # The Windows installer typically places claude under the user profile.
    # Ensure likely locations are on PATH for this process so shutil.which sees it.
    profile = Path(os.environ.get("USERPROFILE", str(Path.home())))
    candidates = [
        profile / ".local" / "bin",
        profile / "AppData" / "Local" / "Programs" / "claude",
        profile / "AppData" / "Roaming" / "npm",
    ]
    for c in candidates:
        if c.exists() and str(c) not in os.environ.get("PATH", "").split(os.pathsep):
            os.environ["PATH"] = str(c) + os.pathsep + os.environ.get("PATH", "")

    claude_path = shutil.which("claude") or shutil.which("claude.exe")
    if claude_path:
        console.print(f"[green]claude now available:[/green] {claude_path}")
        return claude_path

    console.print(
        f"[yellow]claude still not on PATH after install.[/yellow] "
        f"Check {candidates[0]} and ensure it's on your PATH.")
    return None


def health_check() -> dict | None:
    """Poll /health then /stats. Warn (don't exit) on failure."""
    console.print(Panel.fit("[bold cyan]Health-checking the proxy[/]", border_style="cyan"))

    import urllib.request
    import urllib.error

    # Poll /health for up to ~15s.
    health_ok = False
    for _ in range(30):
        try:
            with urllib.request.urlopen(f"{PROXY_URL}/health", timeout=2) as r:
                if 200 <= r.status < 300:
                    health_ok = True
                    break
        except Exception:
            time.sleep(0.5)

    if not health_ok:
        console.print(f"[red]Proxy did not respond healthy at {PROXY_URL}/health[/red]")
        _print_service_status()
        return None
    console.print(f"[green]Proxy healthy at {PROXY_URL}/health[/green]")

    # Poll /stats until the key pool is non-empty. The proxy force-loads keys in
    # its lifespan startup, but the service may still be booting when we first
    # hit it; and even after load, the round-robin store reports total_keys
    # from its in-memory list which is populated on the first /stats call.
    # Wait up to ~20s for keys to actually appear before declaring failure.
    stats = None
    total_keys = 0
    for attempt in range(40):
        try:
            with urllib.request.urlopen(f"{PROXY_URL}/stats", timeout=3) as r:
                stats = json.loads(r.read().decode())
            total_keys = stats.get("total_keys", 0)
            if total_keys >= 1:
                break
        except Exception:
            pass
        time.sleep(0.5)

    if stats is None:
        console.print(f"[red]Could not read /stats after waiting.[/red]")
        _print_service_status()
        return None

    if total_keys < 1:
        console.print(
            f"[red]Proxy is up but reports total_keys={total_keys} after waiting.[/red] "
            "Keys were written to data/keys.txt but the proxy hasn't loaded them. "
            "Check `atlas logs` and `atlas restart`.")
    else:
        console.print(f"[green]Proxy serving with {total_keys} key(s).[/green]")
    return stats


def _service_descriptor() -> tuple[str, str]:
    """Return (label, path) describing the installed service backend for the
    summary table — systemd unit on Linux, LaunchAgent plist on macOS, Windows
    Service on Windows."""
    if IS_MACOS:
        return ("LaunchAgent", f"~/Library/LaunchAgents/{PLIST_LABEL}.plist")
    if IS_WINDOWS:
        return ("Service", WIN_SERVICE_NAME)
    return ("Unit file", str(UNIT_DST))


def _print_service_status() -> None:
    """Print a short service-status excerpt + a hint, non-fatal. Branches on
    the host's service backend."""
    if IS_WINDOWS:
        try:
            out = subprocess.run(
                ["sc", "query", WIN_SERVICE_NAME],
                capture_output=True, text=True, check=False,
            ).stdout
            if out:
                console.print(f"[dim]{out}[/dim]")
        except Exception:
            pass
        console.print("[dim]Inspect logs in the service's log file.[/dim]")
        return

    if IS_MACOS:
        try:
            out = subprocess.run(
                ["launchctl", "list", PLIST_LABEL],
                capture_output=True, text=True, check=False,
            ).stdout
            if out:
                console.print(f"[dim]{out}[/dim]")
        except Exception:
            pass
        console.print("[dim]Inspect logs with: tail -f /tmp/atlas-proxy.log[/dim]")
        return

    # Linux: systemctl.
    if shutil.which("systemctl") is None:
        return
    try:
        out = subprocess.run(
            ["systemctl", "status", SERVICE_NAME, "--no-pager", "-n", "10"],
            capture_output=True, text=True, check=False,
        ).stdout
        console.print(f"[dim]{out}[/dim]")
    except Exception:
        pass
    console.print("[dim]Inspect logs with: atlas logs[/dim]")


def launch_claude(claude_path: str | None, stats: dict | None) -> None:
    """Print a summary, then launch claude to open the TUI. Per failure policy,
    warn if anything is off but still launch (if claude exists). On Unix we
    execvp into claude (mirrors install.sh's exec handoff); on Windows
    os.execvp is unreliable for TUI apps, so we subprocess.run and block."""
    total_keys = (stats or {}).get("total_keys", 0)

    svc_label, svc_path = _service_descriptor()
    cli_label = "CLI" if not IS_WINDOWS else "CLI shim"
    cli_path = str(WIN_CLI_SRC) if IS_WINDOWS else str(CLI_DST)

    summary = Table(title="Atlas install summary", show_header=True, header_style="bold magenta")
    summary.add_column("Field", style="cyan", no_wrap=True)
    summary.add_column("Value", style="green")
    summary.add_row("Service backend", "systemd" if IS_LINUX else
                                 "launchd" if IS_MACOS else "Windows Service")
    summary.add_row(svc_label, svc_path)
    summary.add_row("Port", "8788")
    summary.add_row(cli_label, cli_path)
    summary.add_row("Keys loaded", str(total_keys))
    summary.add_row("Claude", claude_path or "[red]not found[/red]")
    summary.add_row("Project", str(PROJECT_DIR))
    console.print()
    console.print(summary)

    if not claude_path:
        install_hint = (
            "curl -fsSL https://claude.ai/install.sh | bash" if IS_UNIX
            else f"irm {CLAUDE_INSTALL_PS_URL} | iex"
        )
        console.print(
            Panel.fit(
                "[bold red]claude is not installed.[/bold red]\n"
                f"Install it with:  [bold]{install_hint}[/bold]\n"
                "Then run:         [bold]claude[/bold]",
                border_style="red",
            )
        )
        sys.exit(0)

    if total_keys < 1:
        console.print(
            "[yellow]Warning: proxy has no keys loaded — claude will launch but "
            "requests will fail until keys are in data/keys.txt.[/yellow]")

    console.print()
    console.print(Panel.fit(
        "[bold green]Atlas installed. Launching Claude Code...[/bold green]",
        border_style="green"))

    # Set ANTHROPIC_* in this process so the first launch talks to the proxy,
    # even before the user sources their rc file / opens a new shell.
    os.environ["ANTHROPIC_BASE_URL"] = PROXY_URL
    os.environ["ANTHROPIC_API_KEY"] = "atlas"

    # Launch claude. Unix: replace this process (exec handoff). Windows:
    # subprocess.run + block — os.execvp is unreliable for console TUIs there.
    if IS_WINDOWS:
        subprocess.run([claude_path], check=False)
        sys.exit(0)
    os.execvp(claude_path, ["claude"])


def main() -> None:
    console.print(
        Panel.fit(
            "[bold magenta]Atlas[/bold magenta] [dim]NVIDIA proxy installer[/dim]\n"
            "[dim]Port 8788 · NVIDIA-only · Claude Code front-end[/dim]",
            border_style="magenta",
        )
    )

    console.print(f"  [cyan]▸[/cyan] [dim]Project[/dim]   [cyan]{PROJECT_DIR}[/]")
    console.print(f"  [cyan]▸[/cyan] [dim]Venv[/dim]       [cyan]{VENV_DIR}[/]")
    console.print(f"  [cyan]▸[/cyan] [dim]Python[/dim]     [cyan]{PYTHON_BIN}[/]")
    console.print()

    steps = [
        ("Configure .env defaults", configure_env_defaults),
        ("Collect NVIDIA keys", collect_keys),
        ("Install + start service", install_and_start_service),
        ("Install atlas CLI", install_cli),
        ("Wire ANTHROPIC env", wire_claude_env),
        ("Ensure Claude Code", ensure_claude),
        ("Health-check proxy", health_check),
    ]

    claude_path = None
    stats = None
    for label, fn in steps:
        console.print()
        result = fn()
        console.print(f"  [green]✔[/green] [dim]{label}[/dim]")
        # Capture the two return values we need for the final launch.
        if label == "Ensure Claude Code":
            claude_path = result
        elif label == "Health-check proxy":
            stats = result

    launch_claude(claude_path, stats)


if __name__ == "__main__":
    main()
