"""Environment configuration and .env management."""

import os
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .console import get_console
from .platform import PlatformInfo, detect_platform
from .files import append_to_file, ensure_dir, read_file, write_file


console = get_console()


@dataclass
class EnvConfig:
    """Atlas environment configuration."""
    # Proxy
    proxy_host: str = "127.0.0.1"
    proxy_port: int = 8788

    # Provider selection
    provider: str = "openrouter"  # "nvidia" | "openrouter"

    # NVIDIA
    nvidia_base_url: str = "https://integrate.api.nvidia.com/v1/chat/completions"
    nvidia_model: str = "nvidia/nemotron-3-ultra-550b-a55b"
    nvidia_keys_file: str = ""

    # OpenRouter
    openrouter_base_url: str = "https://openrouter.ai/api/v1"
    openrouter_model: str = "nemotron-3-ultra-550b-a55b:free"
    openrouter_keys_file: str = ""

    # Proxy tuning
    proxy_reload_seconds: int = 5
    proxy_cooldown_seconds: int = 45
    proxy_suspend_seconds: int = 600
    proxy_max_errors: int = 8
    proxy_debug: bool = False

    # System prompt override
    system_prompt_override_enabled: bool = True
    system_prompt_override_file: str = ""

    # Computed
    anthropic_base_url: str = field(init=False)
    anthropic_api_key: str = field(init=False)

    def __post_init__(self):
        self.anthropic_base_url = f"http://{self.proxy_host}:{self.proxy_port}"
        self.anthropic_api_key = "atlas"

    def to_env_dict(self) -> dict[str, str]:
        """Convert to environment variable dict."""
        d = {
            "ATLAS_PROXY_HOST": self.proxy_host,
            "ATLAS_PROXY_PORT": str(self.proxy_port),
            "ATLAS_PROVIDER": self.provider,
            "ATLAS_NVIDIA_BASE_URL": self.nvidia_base_url,
            "ATLAS_NVIDIA_MODEL": self.nvidia_model,
            "ATLAS_OPENROUTER_BASE_URL": self.openrouter_base_url,
            "ATLAS_OPENROUTER_MODEL": self.openrouter_model,
            "ATLAS_PROXY_RELOAD_SECONDS": str(self.proxy_reload_seconds),
            "ATLAS_PROXY_COOLDOWN_SECONDS": str(self.proxy_cooldown_seconds),
            "ATLAS_PROXY_SUSPEND_SECONDS": str(self.proxy_suspend_seconds),
            "ATLAS_PROXY_MAX_ERRORS": str(self.proxy_max_errors),
            "ATLAS_PROXY_DEBUG": "1" if self.proxy_debug else "0",
            "SYSTEM_PROMPT_OVERRIDE_ENABLED": "1" if self.system_prompt_override_enabled else "0",
        }
        if self.nvidia_keys_file:
            d["ATLAS_NVIDIA_KEYS_FILE"] = self.nvidia_keys_file
        if self.openrouter_keys_file:
            d["ATLAS_OPENROUTER_KEYS_FILE"] = self.openrouter_keys_file
        if self.system_prompt_override_file:
            d["SYSTEM_PROMPT_OVERRIDE_FILE"] = self.system_prompt_override_file
        return d


DEFAULT_ENV_TEMPLATE = """# Atlas Proxy Configuration
# Generated by atlas-setup — edit freely, rerun setup to regenerate

# Proxy
ATLAS_PROXY_HOST=127.0.0.1
ATLAS_PROXY_PORT=8788

# Provider: nvidia | openrouter
ATLAS_PROVIDER=openrouter

# NVIDIA
ATLAS_NVIDIA_BASE_URL=https://integrate.api.nvidia.com/v1/chat/completions
ATLAS_NVIDIA_MODEL=nvidia/nemotron-3-ultra-550b-a55b
# ATLAS_NVIDIA_KEYS_FILE=/path/to/nvidia_keys.txt

# OpenRouter
ATLAS_OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
ATLAS_OPENROUTER_MODEL=nemotron-3-ultra-550b-a55b:free
# ATLAS_OPENROUTER_KEYS_FILE=/path/to/openroute_keys.txt

# Proxy tuning
ATLAS_PROXY_RELOAD_SECONDS=5
ATLAS_PROXY_COOLDOWN_SECONDS=45
ATLAS_PROXY_SUSPEND_SECONDS=600
ATLAS_PROXY_MAX_ERRORS=8
ATLAS_PROXY_DEBUG=0

# System prompt override
SYSTEM_PROMPT_OVERRIDE_ENABLED=1
# SYSTEM_PROMPT_OVERRIDE_FILE=/root/claude/atlas/data/system_prompt_override.txt
"""


def get_env_path(platform_info: PlatformInfo) -> Path:
    """Get .env file path."""
    return platform_info.project_dir / ".env"


def load_env(path: Path) -> dict[str, str]:
    """Load .env file into dict."""
    env = {}
    content = read_file(path)
    if content:
        for line in content.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            env[key.strip()] = value.strip()
    return env


def write_env(path: Path, config: EnvConfig) -> bool:
    """Write .env file from config."""
    lines = ["# Atlas Proxy Configuration", "# Generated by atlas-setup — edit freely"]
    for key, value in config.to_env_dict().items():
        lines.append(f"{key}={value}")
    return write_file(path, "\n".join(lines) + "\n")


def ensure_env_file(platform_info: PlatformInfo, config: Optional[EnvConfig] = None) -> EnvConfig:
    """Ensure .env exists, create from template if not."""
    env_path = get_env_path(platform_info)
    if env_path.exists():
        console.info(f".env exists: {env_path}")
        existing = load_env(env_path)
        if config is None:
            config = EnvConfig()
        # Update config from existing env
        for key, value in existing.items():
            attr = key.lower()
            if hasattr(config, attr):
                # Type conversion
                current = getattr(config, attr)
                if isinstance(current, bool):
                    value = value.lower() in ("1", "true", "yes", "on")
                elif isinstance(current, int):
                    value = int(value)
                setattr(config, attr, value)
        return config

    config = config or EnvConfig()
    # Set default keys file paths
    data_dir = platform_info.project_dir / "data"
    config.nvidia_keys_file = str(data_dir / "keys.txt")
    config.openrouter_keys_file = str(data_dir / "openroute_keys.txt")
    config.system_prompt_override_file = str(platform_info.project_dir / "data" / "system_prompt_override.txt")

    write_env(env_path, config)
    console.success(f"Created .env: {env_path}")

    # Install shell exports
    install_shell_env(platform_info, config)
    return config


def install_shell_env(platform_info: PlatformInfo, config: EnvConfig) -> bool:
    """Install ANTHROPIC_* exports into shell rc files."""
    if platform_info.is_windows:
        return install_shell_env_windows(config)

    rc_files = []
    shell = platform_info.shell
    if shell == "zsh":
        rc_files = [platform_info.home / ".zshrc", platform_info.home / ".bashrc"]
    elif shell == "fish":
        rc_files = [platform_info.home / ".config" / "fish" / "config.fish"]
    else:
        rc_files = [platform_info.home / ".bashrc", platform_info.home / ".zshrc"]

    marker = "# --- Atlas Proxy (ANTHROPIC_*) ---"
    exports = [
        f'export ANTHROPIC_BASE_URL="http://127.0.0.1:8788"',
        f'export ANTHROPIC_API_KEY="atlas"',
        f'unset ANTHROPIC_AUTH_TOKEN 2>/dev/null || true',
    ]

    success = True
    for rc in rc_files:
        if rc.exists():
            content = read_file(rc) or ""
            if marker in content:
                console.info(f"Already configured in {rc.name}")
                continue
            if append_to_file(rc, [marker] + exports + ["# --- end Atlas ---"]):
                console.success(f"Added ANTHROPIC_* exports to {rc.name}")
            else:
                success = False
        else:
            console.debug(f"Shell rc not found: {rc}")

    return success


def install_shell_env_windows(config: EnvConfig) -> bool:
    """Install env vars on Windows via setx."""
    try:
        for name, value in (
            ("ANTHROPIC_BASE_URL", "http://127.0.0.1:8788"),
            ("ANTHROPIC_API_KEY", "atlas"),
        ):
            subprocess.run(["setx", name, value], check=False,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            console.success(f"setx {name} (persists for new shells)")
        # Clear AUTH_TOKEN if present
        subprocess.run(["reg", "delete", "HKCU\\Environment", "/v", "ANTHROPIC_AUTH_TOKEN", "/f"],
                       check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return True
    except Exception as e:
        console.error(f"Failed to set Windows env: {e}")
        return False