"""System service installation (systemd, launchd, Windows Service)."""

import os
import json
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from .console import get_console
from .files import ensure_dir, read_file, write_file
from .platform import PlatformInfo, detect_platform


console = get_console()


@dataclass
class ServiceConfig:
    """Service configuration."""
    name: str = "atlas-proxy"
    display_name: str = "Atlas Proxy"
    description: str = "Atlas Multi-Provider Proxy (OpenRouter/NVIDIA)"
    working_dir: str = ""
    python_path: str = ""
    module: str = "proxy.main"
    user: str = ""
    env: dict[str, str] = None

    def __post_init__(self):
        if self.env is None:
            self.env = {}


def _sanitize_systemd_value(value: str) -> str:
    """Sanitize value for systemd Environment= line (no newlines, no trailing comments)."""
    return value.replace("\n", " ").replace("\r", " ").strip()


def _sanitize_service_name(name: str) -> str:
    """Validate service name (alphanumeric, dash, underscore only)."""
    import re
    if not re.match(r'^[a-zA-Z0-9_-]+$', name):
        raise ValueError(f"Invalid service name: {name!r} — only alphanumeric, dash, underscore allowed")
    return name


def _validate_absolute_path(path: str, field: str) -> str:
    """Validate path is absolute and safe."""
    p = Path(path)
    if not p.is_absolute():
        raise ValueError(f"{field} must be absolute path: {path!r}")
    # Prevent directory traversal
    try:
        p.resolve()
    except Exception as e:
        raise ValueError(f"Invalid {field}: {e}")
    return str(p)


SYSTEMD_TEMPLATE = """# Atlas Proxy — systemd unit
# Generated by atlas-setup — do not edit manually

[Unit]
Description={description}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={user}
WorkingDirectory={working_dir}
Environment=HOME={home}
Environment=PATH={venv_bin}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
{env_vars}
ExecStart={python_path} -m {module}
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""


LAUNCHD_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{python_path}</string>
        <string>-m</string>
        <string>{module}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>{working_dir}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>{home}</string>
        <key>PATH</key>
        <string>{venv_bin}:/usr/local/bin:/usr/bin:/bin</dict>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/{label}.out.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/{label}.err.log</string>
</dict>
</plist>
"""


WINDOWS_SERVICE_TEMPLATE = '''"""Atlas Proxy Windows Service host."""

import sys
import os
import json
import servicemanager
import win32serviceutil
import win32service
import win32event
import subprocess

class AtlasProxyService(win32serviceutil.ServiceFramework):
    _svc_name_ = "{name}"
    _svc_display_name_ = "{display_name}"
    _svc_description_ = "{description}"

    def __init__(self, args):
        win32serviceutil.ServiceFramework.__init__(self, args)
        self.hWaitStop = win32event.CreateEvent(None, 0, 0, None)
        self.process = None

    def SvcStop(self):
        self.ReportServiceStatus(win32service.SERVICE_STOP_PENDING)
        win32event.SetEvent(self.hWaitStop)
        if self.process:
            self.process.terminate()

    def SvcDoRun(self):
        servicemanager.LogMsg(
            servicemanager.EVENTLOG_INFORMATION_TYPE,
            servicemanager.PYS_SERVICE_STARTED,
            (self._svc_name_, "")
        )
        self.main()

    def main(self):
        env = os.environ.copy()
        {env_setup}
        env.update(json.loads(r"""{env_dict_json}"""))
        self.process = subprocess.Popen(
            [{python_path!r}, "-m", "{module}"],
            cwd={working_dir!r},
            env=env,
        )
        win32event.WaitForSingleObject(self.hWaitStop, win32event.INFINITE)
        if self.process:
            self.process.wait()

if __name__ == "__main__":
    win32serviceutil.HandleCommandLine(AtlasProxyService)
'''


def install_systemd_service(config: ServiceConfig, platform_info: PlatformInfo) -> bool:
    """Install systemd service on Linux."""
    if not platform_info.is_linux:
        return False

    # Check systemctl
    if not shutil.which("systemctl"):
        console.error("systemctl not found")
        return False

    # Validate and sanitize all inputs
    name = _sanitize_service_name(config.name)
    description = config.description.strip()
    user = config.user or os.getenv("SUDO_USER") or os.getenv("USER") or "root"
    working_dir = _validate_absolute_path(config.working_dir, "working_dir")
    python_path = _validate_absolute_path(config.python_path, "python_path")
    module = config.module
    if not module.replace(".", "").replace("_", "").isalnum():
        raise ValueError(f"Invalid module name: {module!r}")
    venv_bin = str(Path(python_path).parent)
    home = str(Path.home())

    # Sanitize env vars for systemd
    env_vars = "\n".join(
        f"Environment={k}={_sanitize_systemd_value(v)}"
        for k, v in config.env.items()
    )

    # Render template
    unit = SYSTEMD_TEMPLATE.format(
        description=description,
        user=user,
        working_dir=working_dir,
        home=home,
        venv_bin=venv_bin,
        python_path=python_path,
        module=module,
        env_vars=env_vars,
    )

    # Write unit file
    unit_path = Path("/etc/systemd/system") / f"{name}.service"
    try:
        if os.geteuid() == 0:
            write_file(unit_path, unit)
        else:
            subprocess.run(
                ["sudo", "tee", str(unit_path)],
                input=unit.encode(),
                check=True,
                stdout=subprocess.DEVNULL,
            )
    except Exception as e:
        console.error(f"Failed to write systemd unit: {e}")
        return False

    # Reload and enable
    try:
        subprocess.run(["systemctl", "daemon-reload"], check=True)
        subprocess.run(["systemctl", "enable", "--now", name], check=True)
        console.success(f"Installed and started systemd service: {name}")
        return True
    except subprocess.CalledProcessError as e:
        console.error(f"Failed to enable/start service: {e}")
        return False


def install_launchd_service(config: ServiceConfig, platform_info: PlatformInfo) -> bool:
    """Install launchd agent on macOS."""
    if not platform_info.is_macos:
        return False

    # Validate and sanitize all inputs
    name = _sanitize_service_name(config.name)
    label = name.replace("-", ".")
    python_path = _validate_absolute_path(config.python_path, "python_path")
    module = config.module
    if not module.replace(".", "").replace("_", "").isalnum():
        raise ValueError(f"Invalid module name: {module!r}")
    working_dir = _validate_absolute_path(config.working_dir, "working_dir")
    venv_bin = str(Path(python_path).parent)
    home = str(Path.home())

    plist = LAUNCHD_TEMPLATE.format(
        label=label,
        python_path=python_path,
        module=module,
        working_dir=working_dir,
        home=home,
        venv_bin=venv_bin,
    )

    plist_dir = Path.home() / "Library" / "LaunchAgents"
    ensure_dir(plist_dir)
    plist_path = plist_dir / f"{label}.plist"

    try:
        write_file(plist_path, plist)
        # Unload if exists
        subprocess.run(["launchctl", "unload", str(plist_path)], check=False)
        # Load new
        subprocess.run(["launchctl", "load", "-w", str(plist_path)], check=True)
        subprocess.run(["launchctl", "start", label], check=True)
        console.success(f"Installed and started launchd agent: {label}")
        return True
    except Exception as e:
        console.error(f"Failed to install launchd agent: {e}")
        return False


def install_windows_service(config: ServiceConfig, platform_info: PlatformInfo) -> bool:
    """Install Windows Service."""
    if not platform_info.is_windows:
        return False

    try:
        import win32serviceutil
    except ImportError:
        console.info("Installing pywin32...")
        subprocess.run([config.python_path, "-m", "pip", "install", "pywin32"], check=True)
        import win32serviceutil

    # Write service module
    service_dir = Path(config.working_dir) / "setup"
    ensure_dir(service_dir)
    service_module = service_dir / "atlas_windows_service.py"

    env_setup = "        env[\"HOME\"] = os.path.expanduser(\"~\")\n"
    # JSON encode the env dict for safe embedding
    env_dict_json = json.dumps(config.env)

    service_code = WINDOWS_SERVICE_TEMPLATE.format(
        name=config.name,
        display_name=config.display_name,
        description=config.description,
        python_path=config.python_path,
        module=config.module,
        working_dir=config.working_dir,
        env_setup=env_setup,
        env_dict_json=env_dict_json,
    )

    write_file(service_module, service_code)

    # Install service
    try:
        subprocess.run([config.python_path, str(service_module), "--install"], check=True)
        subprocess.run([config.python_path, str(service_module), "--start"], check=True)
        console.success(f"Installed and started Windows Service: {config.name}")
        return True
    except Exception as e:
        console.error(f"Failed to install Windows Service: {e}")
        return False


def install_service(config: ServiceConfig, platform_info: PlatformInfo) -> bool:
    """Install service for current platform."""
    if platform_info.is_linux:
        return install_systemd_service(config, platform_info)
    elif platform_info.is_macos:
        return install_launchd_service(config, platform_info)
    elif platform_info.is_windows:
        return install_windows_service(config, platform_info)
    else:
        console.warning(f"No service installer for {platform_info.system}")
        return False


def uninstall_service(name: str, platform_info: PlatformInfo) -> bool:
    """Uninstall service."""
    if platform_info.is_linux:
        try:
            subprocess.run(["systemctl", "disable", "--now", name], check=False)
            unit_path = Path(f"/etc/systemd/system/{name}.service")
            if unit_path.exists():
                unit_path.unlink()
            subprocess.run(["systemctl", "daemon-reload"], check=False)
            console.success(f"Removed systemd service: {name}")
            return True
        except Exception as e:
            console.error(f"Failed to remove systemd service: {e}")
            return False

    elif platform_info.is_macos:
        label = name.replace("-", ".")
        try:
            subprocess.run(["launchctl", "unload", f"~/Library/LaunchAgents/{label}.plist"], check=False)
            plist_path = Path.home() / "Library" / "LaunchAgents" / f"{label}.plist"
            plist_path.unlink(missing_ok=True)
            console.success(f"Removed launchd agent: {label}")
            return True
        except Exception as e:
            console.error(f"Failed to remove launchd agent: {e}")
            return False

    elif platform_info.is_windows:
        try:
            # Get working_dir from the current process or use a default
            working_dir = str(Path.cwd())
            service_module = Path(working_dir) / "setup" / "atlas_windows_service.py"
            if service_module.exists():
                python_path = str(Path(sys.executable))
                subprocess.run([python_path, str(service_module), "--remove"], check=False)
            console.success(f"Removed Windows Service: {name}")
            return True
        except Exception as e:
            console.error(f"Failed to remove Windows Service: {e}")
            return False

    return False