#!/usr/bin/env bash
# Atlas proxy installer.
#
# Usage:
#   ./setup/install.sh                # full install (venv + systemd)
#   ./setup/install.sh --user         # user-mode (no systemd, no sudo)
#   ./setup/install.sh --uninstall    # remove systemd unit + venv
#   ./setup/install.sh --check        # verify install is healthy
#
# Repo-location-agnostic — resolves its own root, so it works whether
# the repo lives at ~/atlas_proxy, ~/proxy, or anywhere else.

set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve repo root
# ---------------------------------------------------------------------------
SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null \
              || python3 -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "${BASH_SOURCE[0]}")"
SETUP_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
REPO_ROOT="$(cd "$SETUP_DIR/.." && pwd)"
SERVICE_NAME="${ATLAS_SERVICE_NAME:-atlas-proxy}"
SERVICE_USER="${ATLAS_SERVICE_USER:-root}"
PY_BIN="${PYTHON:-python3}"
# Binary name installed at /usr/local/bin/<BIN_NAME>.  Default 'atlas' for
# general installs; set ATLAS_BIN_NAME=atlas2 for the DM fork to avoid
# colliding with the upstream bundle's `atlas` command.
BIN_NAME="${ATLAS_BIN_NAME:-atlas}"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '  \033[36m·\033[0m %s\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
fail() { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; exit 1; }

usage() {
    sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
}

ensure_dirs() {
    mkdir -p "$REPO_ROOT/data/openrouter_data" \
             "$REPO_ROOT/data/huggingface_data" \
             "$REPO_ROOT/data/proxy_data" \
             "$REPO_ROOT/data/payloads" \
             "$REPO_ROOT/proxy/logs"
    info "data/ tree ready"
}

ensure_venv() {
    if [[ ! -x "$REPO_ROOT/.venv/bin/python" ]]; then
        bold "Creating venv ($REPO_ROOT/.venv)"
        "$PY_BIN" -m venv "$REPO_ROOT/.venv"
        "$REPO_ROOT/.venv/bin/python" -m pip install -q --upgrade pip wheel
        ok "venv created"
    else
        info "venv already present"
    fi

    bold "Installing requirements"
    "$REPO_ROOT/.venv/bin/python" -m pip install -q -r "$REPO_ROOT/requirements.txt"
    ok "requirements installed"
}

# ---------------------------------------------------------------------------
# systemd unit generation — paths baked from $REPO_ROOT so the unit is
# valid no matter where the repo lives.
# ---------------------------------------------------------------------------
write_unit() {
    local unit_path="$1"
    cat >"$unit_path" <<EOF
# Auto-generated by $SETUP_DIR/install.sh — do not edit by hand.
# Re-run install.sh to refresh after repo moves.
[Unit]
Description=Atlas Translation Proxy
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$REPO_ROOT
EnvironmentFile=-$REPO_ROOT/.env
ExecStart=$REPO_ROOT/.venv/bin/python -m proxy.main
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=$SERVICE_NAME

[Install]
WantedBy=multi-user.target
EOF
    info "wrote $unit_path"
}

install_systemd() {
    command -v systemctl >/dev/null 2>&1 || fail "systemctl not found — use --user mode instead"
    [[ $EUID -eq 0 ]] || fail "systemd install requires root (or use --user)"

    bold "Installing systemd unit"
    local unit="/etc/systemd/system/${SERVICE_NAME}.service"
    if [[ -f "$unit" ]]; then
        # Existing unit: only overwrite if it's ours (matched by marker).
        # Refuse to clobber an operator's hand-written unit pointing at a
        # different repo — silent clobber broke a prod setup today.
        if grep -q "Auto-generated by .*atlas_proxy/setup/install.sh" "$unit"; then
            info "refreshing existing unit (matches our marker)"
        else
            fail "$unit already exists and is NOT ours — refusing to overwrite.
  The existing unit is from a different atlas install. Either:
    - remove it manually (after stopping the service), OR
    - set ATLAS_SERVICE_NAME to a unique name (e.g. atlas-proxy-2)"
        fi
    fi
    write_unit "$unit"
    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME.service" >/dev/null
    ok "enabled $SERVICE_NAME.service"
    info "start with:   systemctl start $SERVICE_NAME"
    info "logs with:    journalctl -u $SERVICE_NAME -f"
}

# ---------------------------------------------------------------------------
# CLI binary install — symlinks atlas/bin/atlas to /usr/local/bin/$BIN_NAME.
# Refuses to clobber an existing non-symlink of the same name.
# ---------------------------------------------------------------------------
install_cli_binary() {
    local src="$REPO_ROOT/atlas/bin/atlas"
    [[ -x "$src" ]] || fail "CLI script not found at $src"

    local dest="/usr/local/bin/$BIN_NAME"

    # If a file already exists at $dest and is NOT our symlink, refuse to
    # clobber it — the operator probably has their own command with that name.
    if [[ -e "$dest" && ! -L "$dest" ]]; then
        warn "$dest exists and is not a symlink — leaving it alone"
        warn "  remove it manually or set ATLAS_BIN_NAME to something else"
        return 1
    fi
    # If the symlink points somewhere wrong, replace it.
    if [[ -L "$dest" ]]; then
        local current
        current="$(readlink -f "$dest" 2>/dev/null || true)"
        if [[ "$current" != "$(readlink -f "$src")" ]]; then
            rm -f "$dest"
        fi
    fi

    ln -sf "$src" "$dest"
    ok "installed CLI: $dest → $src"
    info "use: $BIN_NAME status"
}

uninstall_cli_binary() {
    local dest="/usr/local/bin/$BIN_NAME"
    if [[ -L "$dest" ]]; then
        local current
        current="$(readlink "$dest" 2>/dev/null || true)"
        if [[ "$current" == "$REPO_ROOT/atlas/bin/atlas" ]]; then
            rm -f "$dest"
            ok "removed CLI symlink: $dest"
            return 0
        fi
    fi
    info "CLI symlink $dest not present (or not ours)"
}

do_install() {
    local mode="${1:-system}"
    bold "Atlas proxy installer"
    info "repo: $REPO_ROOT"
    info "service name: $SERVICE_NAME"

    ensure_dirs
    ensure_venv

    if [[ ! -f "$REPO_ROOT/.env" && -f "$REPO_ROOT/.env.example" ]]; then
        cp "$REPO_ROOT/.env.example" "$REPO_ROOT/.env"
        warn "created .env from .env.example — edit it to set keys"
    else
        info ".env present (or .env.example missing — skipped)"
    fi

    if [[ "$mode" == "user" ]]; then
        ok "user-mode install complete (no systemd unit)"
        info "run with: $REPO_ROOT/run.sh --bg"
    else
        install_systemd
    fi
    install_cli_binary
    ok "install complete"
}

do_uninstall() {
    bold "Uninstalling"
    local unit="/etc/systemd/system/${SERVICE_NAME}.service"
    if [[ -f "$unit" ]]; then
        systemctl disable --now "$SERVICE_NAME.service" 2>/dev/null || true
        rm -f "$unit"
        systemctl daemon-reload
        ok "removed systemd unit"
    else
        info "no systemd unit installed"
    fi
    uninstall_cli_binary
    rm -f "$REPO_ROOT/data/run.pid"
    ok "uninstall complete (venv + data preserved)"
}

do_check() {
    bold "Health check"
    local rc=0
    info "repo: $REPO_ROOT"

    # Path resolution
    "$PY_BIN" - "$REPO_ROOT" <<'PY' || rc=1
import os, sys
os.chdir(sys.argv[1])
sys.path.insert(0, ".")
from proxy.config import (
    LISTEN_HOST, LISTEN_PORT,
    KEY_FILE, HF_KEY_FILE, RUNTIME_PROVIDER_FILE,
    SYSTEM_PROMPT_OVERRIDE_FILE, PAYLOAD_DIR, DATA_DIR,
)
print(f"  LISTEN       {LISTEN_HOST}:{LISTEN_PORT}")
print(f"  DATA_DIR     {DATA_DIR}")
print(f"  KEY_FILE     {KEY_FILE}")
print(f"  HF_KEY_FILE  {HF_KEY_FILE}")
print(f"  RUNTIME      {RUNTIME_PROVIDER_FILE}")
print(f"  PROMPT       {SYSTEM_PROMPT_OVERRIDE_FILE}")
print(f"  PAYLOAD_DIR  {PAYLOAD_DIR}")
PY

    # Required dirs
    for d in data/openrouter_data data/huggingface_data data/proxy_data \
             data/payloads proxy/logs; do
        if [[ -d "$REPO_ROOT/$d" ]]; then ok "$d/"; else warn "missing $d/"; rc=1; fi
    done

    # Venv + deps
    if [[ -x "$REPO_ROOT/.venv/bin/python" ]]; then
        ok "venv present"
        if "$REPO_ROOT/.venv/bin/python" -c "import fastapi, uvicorn, httpx, orjson" 2>/dev/null; then
            ok "deps importable"
        else
            warn "deps missing in venv"
            rc=1
        fi
    else
        warn "no venv"
        rc=1
    fi

    # Systemd
    if [[ -f "/etc/systemd/system/${SERVICE_NAME}.service" ]]; then
        ok "systemd unit installed"
    else
        info "no systemd unit (user-mode?)"
    fi

    # CLI binary
    local bin_dest="/usr/local/bin/$BIN_NAME"
    if [[ -L "$bin_dest" ]]; then
        local target
        target="$(readlink "$bin_dest" 2>/dev/null || true)"
        if [[ "$target" == "$REPO_ROOT/atlas/bin/atlas" ]]; then
            ok "CLI symlink: $bin_dest → $target"
        else
            warn "CLI symlink $bin_dest points elsewhere: $target"
        fi
    elif [[ -e "$bin_dest" ]]; then
        warn "$bin_dest exists but is not our symlink"
    else
        info "no CLI symlink ($bin_dest missing)"
    fi

    if [[ $rc -eq 0 ]]; then ok "all green"; else warn "issues above"; fi
    return $rc
}

case "${1:-}" in
    "")             do_install system ;;
    --user)         do_install user ;;
    --uninstall)    do_uninstall ;;
    --check)        do_check ;;
    -h|--help|help) usage ;;
    *)              usage; exit 2 ;;
esac